name: Post screenshots

on:
  pull_request_target:

jobs:
  post:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.11" ]
        os:  [ ubuntu-latest, ]
    defaults:
      run:
        shell: bash
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Create Screenshots
        run: |
          msp simulate --length 1000 --recombination-rate 0.01 --mutation-rate 0.01 100 out.trees
          python -m tsbrowse preprocess out.trees
          python -m tsbrowse screenshot out.tsbrowse mutations
          python -m tsbrowse screenshot out.tsbrowse edges
          python -m tsbrowse screenshot out.tsbrowse nodes

      - name: Generate comment
        run: |
          echo '<details><summary>Screenshots</summary>' > comment.md
          echo >> comment.md
          for img in *.png; do
            data=$(base64 -w 0 "$img")
            echo "![Screenshot](data:image/png;base64,$data)" >> comment.md
            echo >> comment.md
          done
          echo '</details>' >> comment.md

      - name: Post comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const fs = require('fs');
              const comment_body = fs.readFileSync('comment.md', 'utf8');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                body: comment_body,
              });