name: Tests

on:
  pull_request:
  push:
    branches: [main, test]

jobs:
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.0

  test:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.11" ]
        os:  [ ubuntu-latest, ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Tests with numba
        run: coverage run --source=tsbrowse -m pytest -x tests
    
      - name: Create Screenshots
        run: |
          msp simulate --length 1000 --recombination-rate 0.01 --mutation-rate 0.01 100 out.trees
          python -m tsbrowse preprocess out.trees
          python -m tsbrowse screenshot out.tsbrowse mutations
          python -m tsbrowse screenshot out.tsbrowse edges
          python -m tsbrowse screenshot out.tsbrowse nodes
          
      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: "*.png"

      - name: Tests with coverage (no numba)
        run: TSBROWSE_DISABLE_NUMBA=1 coverage run --source=tsbrowse -m pytest -x tests

      - name: Upload coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github